# Generated by Django 3.2 on 2021-06-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_trusty',
        ),
        migrations.AddField(
            model_name='user',
            name='employee_registration',
            field=models.CharField(default=1, max_length=30, verbose_name=' employee registration'),
            preserve_default=False,
        ),
    ]
