# Generated by Django 3.2 on 2021-06-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210622_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_registration',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='matrícula'),
        ),
    ]
