version: '3.1'

services:
  db:
    image: postgres:13.2
    container_name: cpf_db
    restart: always
    environment:
      POSTGRES_DB: cpf
      POSTGRES_USER: cpf
      POSTGRES_PASSWORD: cpf
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    expose:
      - 5432
    ports:
      - 5432:5432

  api:
    image: api
    container_name: cpf_api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  pgdata:
    external: true