# Generated by Django 3.2 on 2021-06-23 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_notificacao_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpfusuario',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='inventariohistorico',
            old_name='usuario',
            new_name='usuario_cpf',
        ),
        migrations.RenameField(
            model_name='pagamento',
            old_name='usuario_rcto',
            new_name='usuario_cpf_pgto',
        ),
        migrations.RemoveField(
            model_name='emprestimoavulso',
            name='usuario_solicitante',
        ),
        migrations.RemoveField(
            model_name='foe',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='gto',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='gto',
            name='usuario_solicitante',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='movimento',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='usuario_pgto',
        ),
        migrations.RemoveField(
            model_name='quebraferramenta',
            name='usuario',
        ),
        migrations.AddField(
            model_name='emprestimoavulso',
            name='usuario_cpf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emprestimoavulso',
            name='usuario_producao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foe',
            name='usuario_producao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gto',
            name='usuario_cpf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gto',
            name='usuario_producao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='usuario_cpf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='usuario_cpf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='usuario_cpf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='usuario_cpf_rcto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quebraferramenta',
            name='usuario_cpf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quebraferramenta',
            name='usuario_producao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cpfusuario',
            unique_together={('cpf', 'usuario')},
        ),
    ]
