# Generated by Django 3.2 on 2021-06-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210623_0916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilSistema',
        ),
        migrations.AlterModelOptions(
            name='notificacao',
            options={'ordering': ['id'], 'verbose_name': 'Notificação', 'verbose_name_plural': 'Notificações'},
        ),
    ]
