# Generated by Django 3.2 on 2021-06-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0004_auto_20210623_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusistema',
            name='grupo',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Group'),
        ),
    ]
