# Generated by Django 3.2 on 2021-06-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0005_menusistema_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusistema',
            name='grupo',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
