# Generated by Django 3.2 on 2021-06-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0006_alter_menusistema_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='modificado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menusistema',
            name='grupo',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
